---
- name: reload systemd
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart backend
  become: yes
  ansible.builtin.systemd:
    name: todolist-backend-{{ backend_version }}
    state: restarted
    daemon_reload: yes
    enabled: yes
