---
- hosts: vm2
  become: yes
  tasks:
    - name: Full system update (apt update && upgrade)
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
      tags: update 

- name: Deploy ToDo List Application
  hosts: vm2
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
 
  roles:
    - postgres
    - backend
    - frontend
