---
- name: Install Go
  apt:
    name: golang
    state: present

- name: Clone repository
  git:
    repo: "{{ backend_repo }}"
    dest: "{{ backend_src_dir }}"
    version: "{{ backend_branch }}"

- name: Install dependencies
  shell: |
    cd {{ backend_code_dir }}
    go mod download

- name: Build backend
  shell: |
    cd {{ backend_code_dir }}
    go build -o todolist-backend

- name: Create systemd service
  template:
    src: backend.service.j2
    dest: /etc/systemd/system/todolist-backend.service
  notify: restart backend

- name: Enable and start service
  systemd:
    name: todolist-backend
    enabled: yes
    state: started
