---
- name: Copy backend files
  become: yes
  copy:
    src: "/opt/todolist/backend/"
    dest: "{{ backend_src_path }}"
    remote_src: yes

- name: Build backend image using docker command
  become: yes
  command: >
    docker build
    --platform linux/amd64
    -t {{ backend_image_name }}
    -f {{ backend_src_path }}/Dockerfile
    {{ backend_src_path }}
  args:
    creates: "{{ backend_image_name }}"
  register: build_result
  changed_when: "'Successfully built' in build_result.stdout"

- name: Run backend container
  community.docker.docker_container:
    name: backend
    image: "{{ backend_image_name }}"
    env_file: "{{ backend_src_path }}/.env"
    ports:
      - "8080:8080"
    networks:
      - name: "{{ network_name }}"
    restart_policy: "unless-stopped"
