---
- name: Install required packages Docker
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
    state: present
    update_cache: yes

- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker packages
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Ensure Docker is running and enabled
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Wait for Docker socket
  wait_for:
    path: "/var/run/docker.sock"
    timeout: 30

- name: Create Docker network
  become: yes
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: bridge
